### PR TITLE
Bump curve25519-dalek version and merge upstream changes

### PR DESCRIPTION
**Pull request by remoun**
* Update `curve25519-dalek` dependency to include https://github.com/mobilecoinfoundation/curve25519-dalek/pull/2
* Merge changes from https://github.com/dalek-cryptography/x25519-dalek/tree/develop

Supports https://github.com/mobilecoinfoundation/mobilecoin/issues/1326

### CODE REVIEW

**Comment by cbeck88** [comment]
This seems really hard to evaluate, can we ask Isis to review this, or make a new release upstream?

**Review by cbeck88 — DISMISSED** [review]
I guess there's not that much that actually changed in the diff

**Review by jcape — DISMISSED** [review]
LGTM pending curve patch location update.

**Comment by remoun** [comment]
PTAL, I've updated the patched curve dep to use the MCF fork.

**Review by jcape — APPROVED** [review]

**Pull request merged**
